HTTP/1.1 200 OK
Date: Wed, 24 Jan 2024 04:41:30 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Report-To: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1702010490&sid=812dcc77-0bd0-43b1-a5f1-b25750382959&s=ufU1u%2Ba%2B7fpGgBuaTER5Dfu7pW4Z7ExIhIBXSnP6A7o%3D"}]}
Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1702010490&sid=812dcc77-0bd0-43b1-a5f1-b25750382959&s=ufU1u%2Ba%2B7fpGgBuaTER5Dfu7pW4Z7ExIhIBXSnP6A7o%3D
Nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=60, s-maxage=3600
Etag: W/"56ea-l6IWlSD3uaJeiLhkqaYERChpQ9Y"
Vary: Accept-Encoding
Content-Encoding: gzip
Via: 1.1 vegur
CF-Cache-Status: DYNAMIC
Strict-Transport-Security: max-age=2592000
Server: cloudflare
CF-RAY: 832256195f84c6a2-SEA
alt-svc: h3=":443"; ma=86400

{
  "id": "47f90d2c-e191-4239-a466-5892ef59a88b",
  "name": "EPCOT",
  "entityType": "PARK",
  "timezone": "America/New_York",
  "children": [
    {
      "id": "5b7cf10a-763b-45ba-9049-87140270826f",
      "name": "La Hacienda de San Angel",
      "entityType": "RESTAURANT",
      "slug": "lahaciendadesanangel",
      "externalId": "15525573;entityType=restaurant"
    },
    {
      "id": "17d51899-7d6d-4cd7-93bb-4064a47d501b",
      "name": "Teppan Edo",
      "entityType": "RESTAURANT",
      "slug": "teppanedo",
      "externalId": "221625;entityType=restaurant"
    },
    {
      "id": "8f353879-d6ac-4211-9352-4029efb47c18",
      "name": "Living with the Land – Glimmering Greenhouses",
      "entityType": "ATTRACTION",
      "slug": "livingwiththeland",
      "externalId": "80010161;entityType=Attraction"
    },
    {
      "id": "3d8f8f8f-f984-4d2e-8dea-5a79432bdf05",
      "name": "Advanced Training Lab",
      "entityType": "ATTRACTION",
      "slug": "advancedtraininglab",
      "externalId": "3831;entityType=Attraction"
    },
    {
      "id": "ade9aa6d-2eb0-4046-b04d-a0f98d0682d9",
      "name": "Sea Turtles - Disney Animals",
      "entityType": "ATTRACTION",
      "slug": "seaturtlesdisneyanimals",
      "externalId": "17883692;entityType=Attraction"
    },
    {
      "id": "66ff36de-9cb3-4d9a-b891-1665d19ffb3e",
      "name": "Stave Church Gallery",
      "entityType": "ATTRACTION",
      "slug": "stavechurchgallery",
      "externalId": "61525;entityType=Attraction"
    },
    {
      "id": "ee070d46-6a64-41c0-9f12-69dcfcca10a0",
      "name": "Reflections of China",
      "entityType": "ATTRACTION",
      "slug": "reflectionsofchina",
      "externalId": "80010180;entityType=Attraction"
    },
    {
      "id": "8d7ccdb1-a22b-4e26-8dc8-65b1938ed5f0",
      "name": "Frozen Ever After",
      "entityType": "ATTRACTION",
      "slug": "frozeneverafter",
      "externalId": "18375495;entityType=Attraction"
    },
    {
      "id": "41aba635-48e4-43bf-9bb1-3b811b5705d0",
      "name": "Rose & Crown Pub Musician",
      "entityType": "SHOW",
      "slug": "epcotpianist",
      "externalId": "17490262;entityType=Entertainment"
    },
    {
      "id": "8410885a-115d-4a5f-9cd5-08d0e659a603",
      "name": "Takumi-Tei",
      "entityType": "RESTAURANT",
      "slug": "takumitei",
      "externalId": "19317888;entityType=restaurant"
    },
    {
      "id": "329c91db-3b4f-40e5-adaa-f902e6f450f9",
      "name": "Coral Reefs - Disney Animals",
      "entityType": "ATTRACTION",
      "slug": "coralreefsdisneyanimals",
      "externalId": "17883690;entityType=Attraction"
    },
    {
      "id": "35ed719b-f7f0-488f-8346-4fbf8055d373",
      "name": "Disney and Pixar Short Film Festival",
      "entityType": "ATTRACTION",
      "slug": "disneyandpixarshortfilmfestival",
      "externalId": "18269694;entityType=Attraction"
    },
    {
      "id": "22f48b73-01df-460e-8969-9eb2b4ae836c",
      "name": "Gran Fiesta Tour Starring The Three Caballeros",
      "entityType": "ATTRACTION",
      "slug": "granfiestatourstarringthethreecaballeros",
      "externalId": "207395;entityType=Attraction"
    },
    {
      "id": "18c533d6-a395-4ae4-9488-80fce9c497fe",
      "name": "Palais du Cinéma",
      "entityType": "ATTRACTION",
      "slug": "palaisducinma",
      "externalId": "19503896;entityType=Attraction"
    },
    {
      "id": "8c8cd77d-97f6-4309-b285-42aad90e9f15",
      "name": "Beauty and the Beast Sing-Along",
      "entityType": "ATTRACTION",
      "slug": "beautyandthebeastsingalong",
      "externalId": "19463785;entityType=Attraction"
    },
    {
      "id": "07dbeaea-85fa-45f2-872f-02f9e7510419",
      "name": "Gallery of Arts and History",
      "entityType": "ATTRACTION",
      "slug": "galleryofartsandhistory",
      "externalId": "80010137;entityType=Attraction"
    },
    {
      "id": "3e5f26ee-c02d-47fd-891e-5e4479073444",
      "name": "ImageWorks - The \"What If\" Labs",
      "entityType": "ATTRACTION",
      "slug": "imageworksthewhatiflabs",
      "externalId": "80010144;entityType=Attraction"
    },
    {
      "id": "00666fe9-7774-4b53-9fb7-3d333f8aa503",
      "name": "Impressions de France",
      "entityType": "ATTRACTION",
      "slug": "impressionsdefrance",
      "externalId": "80010145;entityType=Attraction"
    },
    {
      "id": "6f1d3b25-42c9-4e99-9dce-6c20d7a5deea",
      "name": "Bijutsu-kan Gallery",
      "entityType": "ATTRACTION",
      "slug": "bijutsukangallery",
      "externalId": "80069745;entityType=Attraction"
    },
    {
      "id": "480fde8f-fe58-4bfb-b3ab-052a39d4db7c",
      "name": "Spaceship Earth",
      "entityType": "ATTRACTION",
      "slug": "spaceshipearth",
      "externalId": "80010191;entityType=Attraction"
    },
    {
      "id": "37bb0aca-0dcf-4fa0-bc03-81d1b4ef9ac0",
      "name": "Manatees - Disney Animals",
      "entityType": "ATTRACTION",
      "slug": "manateesdisneyanimals",
      "externalId": "19440020;entityType=Attraction"
    },
    {
      "id": "4f0df9e7-d4c1-45b5-93e2-4a7bc92547b0",
      "name": "American Heritage Gallery",
      "entityType": "ATTRACTION",
      "slug": "americanheritagegallery",
      "externalId": "26421;entityType=Attraction"
    },
    {
      "id": "8a877212-9020-43d2-9ead-604b392d8cce",
      "name": "Restaurant Marrakesh",
      "entityType": "RESTAURANT",
      "slug": "restaurantmarrakesh",
      "externalId": "90002068;entityType=restaurant"
    },
    {
      "id": "e6838b82-9927-4ab4-adee-5ceb9c12ce43",
      "name": "Between the Morocco and France Pavilions – Hanukkah Storyteller",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "17186496;entityType=Entertainment"
    },
    {
      "id": "296d164a-8b9a-49d3-a285-637b86731260",
      "name": "Matsuriza",
      "entityType": "SHOW",
      "slug": "matsuriza",
      "externalId": "80010865;entityType=Entertainment"
    },
    {
      "id": "83fed9d1-c25f-497c-ab8e-21e4dd7ce655",
      "name": "Sergio",
      "entityType": "SHOW",
      "slug": "sergio",
      "externalId": "80010873;entityType=Entertainment"
    },
    {
      "id": "4d34dd80-4042-4ada-a74f-ef35a0887b4f",
      "name": "Sharks and Rays - Disney Animals",
      "entityType": "ATTRACTION",
      "slug": "sharksandraysdisneyanimals",
      "externalId": "17883691;entityType=Attraction"
    },
    {
      "id": "15107c34-65a3-473c-aaeb-655b508f529d",
      "name": "Space 220 Lounge",
      "entityType": "RESTAURANT",
      "slug": null,
      "externalId": "19634138;entityType=restaurant"
    },
    {
      "id": "c5f6c7e4-d5cd-4d71-8e02-57d8bb43b3ba",
      "name": "Voices of Liberty",
      "entityType": "SHOW",
      "slug": "voicesofliberty",
      "externalId": "80010879;entityType=Entertainment"
    },
    {
      "id": "fb076275-0570-4d62-b2a9-4d6515130fa3",
      "name": "The Seas with Nemo & Friends",
      "entityType": "ATTRACTION",
      "slug": "theseaswithnemofriends",
      "externalId": "107785;entityType=Attraction"
    },
    {
      "id": "ea730d0c-7723-429d-89a4-9e76f053f5ac",
      "name": "Mariachi Cobre",
      "entityType": "SHOW",
      "slug": "mariachicobre",
      "externalId": "19322758;entityType=Entertainment"
    },
    {
      "id": "9244365a-ffad-4ea1-ad8d-a36ac3a0e383",
      "name": "Reef Fish - Disney Animals",
      "entityType": "ATTRACTION",
      "slug": "reeffishdisneyanimals",
      "externalId": "18672355;entityType=Attraction"
    },
    {
      "id": "57acb522-a6fc-4aa4-a80e-21f21f317250",
      "name": "Turtle Talk With Crush",
      "entityType": "ATTRACTION",
      "slug": "turtletalkwithcrush",
      "externalId": "62992;entityType=Attraction"
    },
    {
      "id": "001b099f-4db8-4843-8c1e-852e0e8fc2df",
      "name": "Viva Mexico",
      "entityType": "SHOW",
      "slug": "vivamexico",
      "externalId": "209984;entityType=Entertainment"
    },
    {
      "id": "9053240b-7f7f-44fe-970b-bd7956cd5d4f",
      "name": "Project Tomorrow: Inventing the Wonders of the Future",
      "entityType": "ATTRACTION",
      "slug": "projecttomorrowinventingthewondersofthefuture",
      "externalId": "220239;entityType=Attraction"
    },
    {
      "id": "87d6511a-42fc-45ab-be8b-550b7f49fb04",
      "name": "Mexico Pavilion – Las Posadas Celebration",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245264;entityType=Entertainment"
    },
    {
      "id": "2ecc4fff-2994-476f-9926-24a4af173838",
      "name": "Bruce's Shark World",
      "entityType": "ATTRACTION",
      "slug": "brucessharkworld",
      "externalId": "56404;entityType=Attraction"
    },
    {
      "id": "8f8746cb-c714-4c60-848d-e2dc4e6f586b",
      "name": "Mexico Folk Art Gallery",
      "entityType": "ATTRACTION",
      "slug": "mexicofolkartgallery",
      "externalId": "80069743;entityType=Attraction"
    },
    {
      "id": "dae68dee-dfba-4128-b594-6aa12add1070",
      "name": "Journey of Water, Inspired by Moana",
      "entityType": "ATTRACTION",
      "slug": null,
      "externalId": "411794307;entityType=Attraction"
    },
    {
      "id": "c9e1d1f6-021f-43f2-a14b-3e67f65adbc4",
      "name": "Biergarten Restaurant",
      "entityType": "RESTAURANT",
      "slug": "biergartenrestaurant",
      "externalId": "90001292;entityType=restaurant"
    },
    {
      "id": "4807262a-ad16-4d43-a0d7-64b24603ef36",
      "name": "Chefs de France",
      "entityType": "RESTAURANT",
      "slug": "chefsdefrance",
      "externalId": "90001373;entityType=restaurant"
    },
    {
      "id": "eb6a60d7-b354-47a1-a091-0beb11b24188",
      "name": "Akershus Royal Banquet Hall",
      "entityType": "RESTAURANT",
      "slug": "akershusroyalbanquethall",
      "externalId": "90002066;entityType=restaurant"
    },
    {
      "id": "605d5f43-06bd-42fe-b5ff-1e0af539654a",
      "name": "Japan Pavilion – Daruma Storyteller",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245268;entityType=Entertainment"
    },
    {
      "id": "3ace01d1-15fc-4fbb-99e4-81a696cb2d05",
      "name": "Kidcot Fun Stops",
      "entityType": "ATTRACTION",
      "slug": "kidcotfunstops",
      "externalId": "91245;entityType=Attraction"
    },
    {
      "id": "67b07a13-cfdf-45b0-a464-8e315a31312c",
      "name": "Norway Pavilion – A Mischievous Magical Barn Santa",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "19423795;entityType=Entertainment"
    },
    {
      "id": "dbf4a977-a7b5-41db-a9b7-ecad65f9aa0f",
      "name": "Spice Road Table",
      "entityType": "RESTAURANT",
      "slug": "spiceroadtable",
      "externalId": "17720675;entityType=restaurant"
    },
    {
      "id": "e14e439d-d1aa-4f3a-90e9-60c524bd0b5a",
      "name": "Tutto Italia Ristorante",
      "entityType": "RESTAURANT",
      "slug": "tuttoitaliaristorante",
      "externalId": "220739;entityType=restaurant"
    },
    {
      "id": "38892221-f69c-4913-97c9-7473c88854fa",
      "name": "Coral Reef Restaurant",
      "entityType": "RESTAURANT",
      "slug": "coralreefrestaurant",
      "externalId": "90001416;entityType=restaurant"
    },
    {
      "id": "3206e3a6-cbc3-4960-9700-163764bc47d6",
      "name": "Le Cellier Steakhouse",
      "entityType": "RESTAURANT",
      "slug": "lecelliersteakhouse",
      "externalId": "90001798;entityType=restaurant"
    },
    {
      "id": "6ecdbfc8-85c2-436d-893b-6db0f437b74a",
      "name": "Rose & Crown Dining Room",
      "entityType": "RESTAURANT",
      "slug": "rosecrowndiningroom",
      "externalId": "90002084;entityType=restaurant"
    },
    {
      "id": "37ae57c5-feaf-4e47-8f27-4b385be200f0",
      "name": "Test Track",
      "entityType": "ATTRACTION",
      "slug": "testtrack",
      "externalId": "80010199;entityType=Attraction"
    },
    {
      "id": "5b6475ad-4e9a-4793-b841-501aa382c9c0",
      "name": "Mission: SPACE",
      "entityType": "ATTRACTION",
      "slug": "missionspace",
      "externalId": "80010173;entityType=Attraction"
    },
    {
      "id": "0f40274d-420a-425a-9377-29fd6e49484f",
      "name": "House of the Whispering Willows",
      "entityType": "ATTRACTION",
      "slug": "houseofthewhisperingwillows",
      "externalId": "160914;entityType=Attraction"
    },
    {
      "id": "75449e85-c410-4cef-a368-9d2ea5d52b58",
      "name": "Journey Into Imagination With Figment",
      "entityType": "ATTRACTION",
      "slug": "journeyintoimaginationwithfigment",
      "externalId": "80010152;entityType=Attraction"
    },
    {
      "id": "59077748-411e-432e-bb9b-4b77942e5a50",
      "name": "Italy Pavilion – La Befana",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245263;entityType=Entertainment"
    },
    {
      "id": "1f542745-cda1-4786-a536-5fff373e5964",
      "name": "The American Adventure",
      "entityType": "ATTRACTION",
      "slug": "theamericanadventure",
      "externalId": "80010200;entityType=Attraction"
    },
    {
      "id": "9d17a505-dc4f-4502-a999-0c6af6272672",
      "name": "China Pavilion – Chinese Lion Dancer",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245272;entityType=Entertainment"
    },
    {
      "id": "b83b6dc9-9573-4e15-ab00-9ed8a2334770",
      "name": "Via Napoli Ristorante e Pizzeria",
      "entityType": "RESTAURANT",
      "slug": "vianapoliristoranteepizzeria",
      "externalId": "15525574;entityType=restaurant"
    },
    {
      "id": "93843fb0-ee5a-49c6-91a8-40a042e93865",
      "name": "Monsieur Paul",
      "entityType": "RESTAURANT",
      "slug": "monsieurpaul",
      "externalId": "90001296;entityType=restaurant"
    },
    {
      "id": "dec242f1-31bf-42ef-86f7-f5358f2f2359",
      "name": "France Pavilion – Père Noël",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245274;entityType=Entertainment"
    },
    {
      "id": "736b2e6c-daaf-45c4-ba9e-fb60d7cf92d6",
      "name": "La Cava del Tequila",
      "entityType": "RESTAURANT",
      "slug": "lacavadeltequila",
      "externalId": "348023;entityType=restaurant"
    },
    {
      "id": "d4179c4c-eb08-4559-aa7c-f9802fda641b",
      "name": "Garden Grill Restaurant",
      "entityType": "RESTAURANT",
      "slug": "gardengrillrestaurant",
      "externalId": "90002237;entityType=restaurant"
    },
    {
      "id": "7969166f-feef-4350-b26e-6a6c745528f4",
      "name": "SeaBase",
      "entityType": "ATTRACTION",
      "slug": "seabase",
      "externalId": "80010184;entityType=Attraction"
    },
    {
      "id": "61fb49f8-e62f-4e1c-ae0e-8ab9929037bc",
      "name": "Canada Far and Wide in Circle-Vision 360",
      "entityType": "ATTRACTION",
      "slug": "canadafarandwideincirclevision360",
      "externalId": "80010174;entityType=Attraction"
    },
    {
      "id": "60cd5f33-55a5-42f2-9f54-541db58149b8",
      "name": "JOYFUL! A Celebration of the Season",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "3427049;entityType=Entertainment"
    },
    {
      "id": "1e735ffb-4868-47f1-b2cd-2ac1156cd5f0",
      "name": "Remy's Ratatouille Adventure",
      "entityType": "ATTRACTION",
      "slug": "remysratatouilleadventureopeningoctober12021",
      "externalId": "19497835;entityType=Attraction"
    },
    {
      "id": "482169b9-2889-4747-8aef-f9d13a37d940",
      "name": "Awesome Planet",
      "entityType": "ATTRACTION",
      "slug": "awesomeplanet",
      "externalId": "19473173;entityType=Attraction"
    },
    {
      "id": "07263f57-0431-4da2-a8b6-77d2965a6f83",
      "name": "San Angel Inn Restaurante",
      "entityType": "RESTAURANT",
      "slug": "sanangelinnrestaurante",
      "externalId": "90002100;entityType=restaurant"
    },
    {
      "id": "cc898103-f9c4-41a5-bf70-26aa5a4d8a96",
      "name": "Meet Joy Inside ImageWorks",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "18409487;entityType=Entertainment"
    },
    {
      "id": "e8dccc86-cfb4-44c3-9a90-e95b88edbd21",
      "name": "Nine Dragons Restaurant",
      "entityType": "RESTAURANT",
      "slug": "ninedragonsrestaurant",
      "externalId": "90001985;entityType=restaurant"
    },
    {
      "id": "7b79e739-c540-4ea5-a4c8-f8d8bac5719b",
      "name": "Meet Mulan in China",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "268742;entityType=Entertainment"
    },
    {
      "id": "86ea784f-eed1-4696-ac01-ebb65589bf0e",
      "name": "Invertebrates at EPCOT - Disney Animals",
      "entityType": "ATTRACTION",
      "slug": "invertebratesatepcotdisneyanimals",
      "externalId": "18673469;entityType=Attraction"
    },
    {
      "id": "e3549451-b284-453d-9c31-e3b1207abd79",
      "name": "Guardians of the Galaxy: Cosmic Rewind",
      "entityType": "ATTRACTION",
      "slug": null,
      "externalId": "411499845;entityType=Attraction"
    },
    {
      "id": "3dbf1ff2-eee0-44a9-8cd9-22bf920e81e9",
      "name": "Luminous The Symphony of Us – Starting December 5, 2023",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "412008998;entityType=Entertainment"
    },
    {
      "id": "09120193-f2db-4073-8ea8-be994e61e5b3",
      "name": "Spaceship Earth: A Beacon of Magic",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "411500814;entityType=Entertainment"
    },
    {
      "id": "5979b17a-4af3-449d-8d9c-3ca312d1f3da",
      "name": "Alberta Bound",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "78700;entityType=Entertainment"
    },
    {
      "id": "b772df79-1fca-4c0a-a2f3-88b22e63e7c3",
      "name": "Space 220 Restaurant",
      "entityType": "RESTAURANT",
      "slug": "space220comingsoon",
      "externalId": "19433706;entityType=restaurant"
    },
    {
      "id": "81e6f8fc-068c-4d20-9433-2353992cec7a",
      "name": "Disney® Visa® Cardmember Photo Opportunity at EPCOT",
      "entityType": "SHOW",
      "slug": "disneyvisacardmemberphotoopportunityatepcot",
      "externalId": "15958368;entityType=Entertainment"
    },
    {
      "id": "81b15dfd-cf6a-466f-be59-3dd65d2a2807",
      "name": "Soarin' Over California",
      "entityType": "ATTRACTION",
      "slug": "soarinaroundtheworld",
      "externalId": "20194;entityType=Attraction"
    },
    {
      "id": "76eadac1-cdfa-45e5-a25c-54ed4c3a604f",
      "name": "Marimba de las Américas",
      "entityType": "SHOW",
      "slug": "marimbadelasamricas",
      "externalId": "19277873;entityType=Entertainment"
    },
    {
      "id": "3beaa9a5-6404-4446-bfd1-e0d0eea65e85",
      "name": "JAMMitors",
      "entityType": "SHOW",
      "slug": "jammingardeners",
      "externalId": "13507;entityType=Entertainment"
    },
    {
      "id": "ec3e507a-86a4-4a87-9fff-457893613ed7",
      "name": "Canada Pavilion – Canadian Holiday Voyageurs",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245275;entityType=Entertainment"
    },
    {
      "id": "33bd3bad-6803-4c5e-97ac-f7e31261a604",
      "name": "Meet Anna and Elsa at Royal Sommerhus",
      "entityType": "SHOW",
      "slug": "meetannaandelsaatroyalsommerhus",
      "externalId": "17564219;entityType=Entertainment"
    },
    {
      "id": "48e7f9f2-ddc3-4ced-8d11-a5cd968085c2",
      "name": "Shiki-Sai: Sushi Izakaya",
      "entityType": "RESTAURANT",
      "slug": "tokyodining",
      "externalId": "221626;entityType=restaurant"
    },
    {
      "id": "fc64aa10-290f-472e-9fab-4d649f53ab2d",
      "name": "La Crêperie de Paris",
      "entityType": "RESTAURANT",
      "slug": null,
      "externalId": "19511274;entityType=restaurant"
    },
    {
      "id": "f8dfc8f9-09e8-4b8c-b478-ee0d926eb76a",
      "name": "Holidays: United Kingdom featuring Father Christmas",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245270;entityType=Entertainment"
    },
    {
      "id": "1d7266ee-bedd-49d8-abca-29625ba5030d",
      "name": "Meet a Friend from the Hundred Acre Wood in the United Kingdom",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "13625;entityType=Entertainment"
    },
    {
      "id": "e9c1bff6-c9c1-4275-8f3d-44226f0fdfbb",
      "name": "Meet Princess Aurora in France",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "15574092;entityType=Entertainment"
    },
    {
      "id": "dce3bd18-3981-4273-8d0f-762f1ebf84a2",
      "name": "Meet Favorite Disney Pals at Disney and Pixar Short Film Festival",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "19493168;entityType=Entertainment"
    },
    {
      "id": "016df02f-6a75-4ca3-88b1-b2cd2d4f200b",
      "name": "Holidays: See Santa at American Adventure",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "245271;entityType=Entertainment"
    },
    {
      "id": "9d3adf0b-f0bf-43c6-b92f-90236880d3db",
      "name": "Groovin' Alps",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "18923661;entityType=Entertainment"
    },
    {
      "id": "e48629ab-939f-4fe0-9e6a-6ad29b8added",
      "name": "Command Performance",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "411702927;entityType=Entertainment"
    },
    {
      "id": "5cd0aeed-2e8a-41c8-9a33-55eb5b121962",
      "name": "Atlas Fusion",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "19496225;entityType=Entertainment"
    },
    {
      "id": "99087d9a-4380-4ab6-b088-20816e233c6f",
      "name": "Meet Asha Near World Showcase Plaza",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "412026226;entityType=Entertainment"
    },
    {
      "id": "64f25dcf-66cb-4b07-b081-6c3f77d46b65",
      "name": "EPCOT Forever",
      "entityType": "SHOW",
      "slug": "epcotforever",
      "externalId": "19258170;entityType=Entertainment"
    },
    {
      "id": "c49ec22b-b529-4d25-bafa-e222b22ddc3c",
      "name": "Harmonious – Now Through April 2, 2023",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "19622841;entityType=Entertainment"
    },
    {
      "id": "a70b81bf-2934-433c-9723-afb2f24112bf",
      "name": "Meet Figment Inside ImageWorks",
      "entityType": "SHOW",
      "slug": null,
      "externalId": "411994369;entityType=Entertainment"
    }
  ]
}